import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
await page.locator('a').filter({ hasText: 'Configuración' }).click();
await page.getByRole('link', { name: 'Preferencias Operativas' }).click();
await page.getByRole('heading', { name: 'Cobros con Tarjeta ►' }).click();
  await page.goto('https://apps-test.magiis.com/#/home/carrier');
  await page.getByRole('banner').getByRole('link', { name: 'Nuevo Viaje' }).click();
  await page.locator('#clientSelect').getByText('Seleccione Usuario').click();
  await page.getByRole('textbox', { name: 'Usuario a Buscar' }).fill('eman');
  await page.getByText('Restrepo, Emanuel (+').click();
  await page.getByText('Cazadores 1987, Buenos Aires').click();
  await page.getByText('Reconquista 661, Buenos Aires').click();
  await page.locator('.bootstrap.width-combo.input-search.ng-untouched.ng-pristine.ng-valid > .below > .single > .placeholder').click();
  await page.getByText('Cazadores 1987, Buenos Aires').click();
  await page.locator('.data-with-icon-col.option-content-container.ng-tns-c16-2').click();
  await page.locator('.ng-star-inserted.highlighted > .data-with-icon-col').click();
  await page.locator('iframe[name="__privateStripeFrame1523"]').contentFrame().getByRole('textbox', { name: 'Credit or debit card number' }).click();
  await page.locator('iframe[name="__privateStripeFrame1523"]').contentFrame().getByRole('textbox', { name: 'Credit or debit card number' }).fill('4000002760003184');
  await page.locator('iframe[name="__privateStripeFrame1524"]').contentFrame().getByRole('textbox', { name: 'Credit or debit card' }).click();
  await page.locator('iframe[name="__privateStripeFrame1523"]').contentFrame().getByRole('textbox', { name: 'Credit or debit card number' }).fill('4000 0027 6000 31842');
  await page.locator('.stripe-element-wrapper.stripe-element-small').first().click();
  await page.locator('iframe[name="__privateStripeFrame1523"]').contentFrame().getByRole('textbox', { name: 'Credit or debit card number' }).fill('4000 0027 6000 31844');
  await page.locator('iframe[name="__privateStripeFrame1524"]').contentFrame().getByRole('textbox', { name: 'Credit or debit card' }).fill('12 / 34');
  await page.locator('iframe[name="__privateStripeFrame1525"]').contentFrame().getByRole('textbox', { name: 'Credit or debit card CVC/CVV' }).click();
  await page.locator('iframe[name="__privateStripeFrame1524"]').contentFrame().getByRole('textbox', { name: 'Credit or debit card' }).click();
  await page.locator('iframe[name="__privateStripeFrame1524"]').contentFrame().getByRole('textbox', { name: 'Credit or debit card' }).fill('12 / 342');
  await page.locator('iframe[name="__privateStripeFrame1525"]').contentFrame().getByRole('textbox', { name: 'Credit or debit card CVC/CVV' }).click();
  await page.locator('iframe[name="__privateStripeFrame1525"]').contentFrame().getByRole('textbox', { name: 'Credit or debit card CVC/CVV' }).fill('123');
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('wmanuel restrepo');
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).fill('534534543543');
  await page.getByRole('button', { name: 'Validar' }).click();
  await page.locator('iframe[name="__privateStripeFrame15211"]').contentFrame().locator('iframe[name="stripe-challenge-frame"]').contentFrame().getByRole('button', { name: 'Complete' }).click();
  await page.getByRole('button', { name: 'Seleccionar Vehículo' }).click();
  await page.getByRole('button', { name: 'Enviar Servicio' }).click();
  await page.locator('iframe[name="__privateStripeFrame15214"]').contentFrame().locator('iframe[name="stripe-challenge-frame"]').contentFrame().getByRole('button', { name: 'Complete' }).click();
});