import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://apps-test.magiis.com/#/home/carrier/dashboard');
  await page.getByRole('banner').getByRole('link', { name: 'Nuevo Viaje' }).click();
  await page.locator('#clientSelect').getByText('Seleccione Usuario').click();
  await page.getByRole('textbox', { name: 'Usuario a Buscar' }).fill('fast');
  await page.locator('.data-with-icon-col').click();
  await page.getByText('Seleccione Usuario').click();
  await page.getByRole('textbox', { name: 'Usuario a Buscar' }).fill('ema');
  await page.locator('.highlighted > .data-with-icon-col').click();
  await page.getByText('Regular').click();
  await page.getByText('Prueba Quotes').click();
  await page.getByRole('button', { name: 'Distancia' }).click();
  await page.getByRole('button', { name: 'A Disposición' }).click();
  await page.locator('#add_rental_hours').click();
  await page.locator('#add_rental_hours').fill('8');
  await page.locator('.ng-tns-c27-2.ng-untouched > div > .search-container > .search-container-input > .bootstrap > .below > .single > .placeholder').first().click();
  await page.getByRole('textbox', { name: 'Ingrese una dirección' }).fill('cazadores 1987');
  await page.getByText('Cazadores 1987, Buenos Aires').click();
  await page.getByText('Cazadores 1987, Buenos Aires').nth(1).click();
  await page.getByRole('textbox', { name: 'Ingrese una dirección' }).fill('la pampa 915');
  await page.getByText('La Pampa 915, Pilar, Buenos').click();
  await page.locator('.data-with-icon-col.option-content-container.ng-tns-c27-2').click();
  await page.getByRole('listitem').filter({ hasText: 'Cuenta Corriente' }).click();
  await page.locator('.round-inline > div > .round > label').first().click();
  await page.locator('div:nth-child(2) > .round > label').first().click();
  await page.locator('.bootstrap.width-combo.input-search.ng-valid.ng-dirty > .below > .single > .toggle').first().click();
  await page.locator('#id_tab_add_travel > div:nth-child(8)').click();
  await page.getByText('✕').nth(3).click();
  await page.getByText('✕').nth(3).click();
  await page.locator('.bootstrap.width-combo.input-search.ng-dirty > .below > .single > .placeholder').first().click();
  await page.getByText('Cazadores 1987, Ciudad Autó').click();
  await page.getByText('✕').nth(4).click();
  await page.locator('.focus > .single > .toggle').click();
  await page.getByRole('textbox', { name: 'Ingrese una dirección' }).fill('reconquista 661');
  await page.getByRole('listitem').filter({ hasText: 'Reconquista 661, Buenos Aires' }).click();
  await page.locator('.btn.btn-primary.rounded-btn.btn-wait-time').first().click();
  await page.locator('.timepicker-group > button').first().click();
  await page.getByRole('textbox', { name: 'Instrucciones' }).click();
  await page.getByRole('textbox', { name: 'Instrucciones' }).fill('test case instrucciones espera en direcci');
  await page.getByRole('textbox', { name: 'Instrucciones' }).press('Dead');
  await page.getByRole('textbox', { name: 'Instrucciones' }).fill('test case instrucciones espera en dirección origen');
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await page.locator('.container-extra-button.adjust-margin > .btn').click();
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('30');
  await page.getByRole('textbox', { name: 'Instrucciones' }).click();
  await page.getByRole('textbox', { name: 'Instrucciones' }).fill('test case nota intrucciones de espera en lugar destino');
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await page.locator('.multiple-destination-container > div > div:nth-child(3)').click();
  await page.getByRole('button', { name: 'Distancia' }).click();
  await page.locator('.multiple-destination-container > div > div:nth-child(3)').click();
  await page.locator('#serviceTypeId').getByText('✕').click();
  await page.getByText('Prueba Quotes').click();
  await page.locator('.container-extra-button.adjust-margin > .btn').click();
  await page.getByRole('textbox', { name: 'Instrucciones' }).click();
  await page.getByText('Tiempo de Espera en Parada 1 (HH:MM) : Instrucciones').click();
  await page.getByRole('textbox', { name: 'Instrucciones' }).click();
  await page.getByRole('textbox', { name: 'Instrucciones' }).fill('test case nota intrucciones de espera en direcci');
  await page.getByRole('textbox', { name: 'Instrucciones' }).press('Dead');
  await page.getByRole('textbox', { name: 'Instrucciones' }).fill('test case nota intrucciones de espera en dirección parada');
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await page.locator('.multiple-destination-container.ng-untouched.ng-valid.ng-dirty > div > div:nth-child(3) > .btn > .fa').click();
  await page.getByText('Parada 1', { exact: true }).click();
  await page.getByText('Parada 1', { exact: true }).click();
  await page.getByText('Parada 2').click();
  await page.getByText('Destino').first().click();
  await page.locator('div:nth-child(3) > .stop > .multiple-destination-container > div > div:nth-child(3) > .btn > .fa').click();
  await page.getByText('Reconquista 661, Buenos Aires').nth(1).click();
  await page.getByRole('textbox', { name: 'Ingrese una dirección' }).fill('san martin 536');
  await page.getByText('San Martín 536, AAL, Buenos').click();
  await page.getByText('Reconquista 661, Buenos Aires').nth(1).click();
  await page.getByRole('textbox', { name: 'Ingrese una dirección' }).fill('la pampa 915');
  await page.getByText('La Pampa 915, Pilar, Buenos').click();
  await page.getByRole('button', { name: 'Configurar', exact: true }).click();
  await page.getByRole('textbox', { name: 'General' }).click();
  await page.getByRole('textbox', { name: 'General' }).fill('nota general');
  await page.getByRole('textbox', { name: 'Origen * Destino Inicio *' }).click();
  await page.getByRole('textbox', { name: 'Parada 2: San Martín 536, AAL' }).click();
  await page.getByRole('textbox', { name: 'Parada 2: San Martín 536, AAL' }).fill('nota segunda parada');
  await page.getByRole('textbox', { name: 'Parada 3: La Pampa 915, Pilar' }).click();
  await page.getByRole('textbox', { name: 'Parada 3: La Pampa 915, Pilar' }).fill('nota tercera parada');
  await page.getByRole('textbox', { name: 'Destino: Reconquista 661,' }).click();
  await page.getByRole('textbox', { name: 'Destino: Reconquista 661,' }).fill('nota para destino');
  await page.locator('.modal-body.ng-star-inserted > div > .form-group').click();
  await page.getByRole('textbox', { name: 'Nota privada' }).click();
  await page.getByRole('textbox', { name: 'Nota privada' }).fill('nota privada solo para chofer');
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await page.locator('#areaId > .below > .single > .value').click();
  await page.locator('#areaId').getByRole('listitem').filter({ hasText: 'IT' }).click();
  await page.locator('.gm-style > div > div:nth-child(2)').click();
  await page.locator('.gm-style > div > div:nth-child(2)').click();
  await page.locator('.gm-style > div > div:nth-child(2)').click();
  await page.locator('.gm-style > div > div:nth-child(2)').click();
  await page.getByRole('button', { name: 'Seleccionar Vehículo' }).click();
  await page.locator('li:nth-child(2) > .card-vehicle > .vehicle-img').click();
  await page.getByRole('heading', { name: 'Standard' }).click();
  await page.locator('li:nth-child(2) > .card-vehicle > .vehicle-img').click();
  await page.getByRole('button', { name: 'SIN PROPINA' }).click();
  await page.getByRole('button', { name: '% 10' }).click();
  await page.getByRole('button', { name: '% 15' }).click();
  await page.getByRole('button', { name: '% 20' }).click();
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).fill('100');
  await page.locator('.form-group > .form-group > .switch > .switch-label').first().click();
  await page.locator('.form-group > .form-group > .switch > .switch-label').first().click();
  await page.getByRole('spinbutton').fill('1000');
  await page.getByRole('heading', { name: '► Otros Costos' }).click();
  await page.getByRole('heading', { name: 'Tiempo de Espera (2:00)' }).click();
  await page.getByRole('heading', { name: '► Otros Costos' }).click();
  await page.locator('.plus-button > .fa').click();
  await page.getByText('Otro Costo').nth(2).click();
  await page.getByRole('listitem').filter({ hasText: 'MEET AND GREET' }).click();
  await page.locator('.column > .input-group').click();
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await page.getByRole('button', { name: 'Volver' }).click();
  await page.getByRole('banner').getByRole('link', { name: 'Nuevo Viaje' }).click();
  await page.locator('#clientSelect').getByText('Seleccione Usuario').click();
  await page.getByRole('textbox', { name: 'Usuario a Buscar' }).fill('fast');
  await page.getByRole('button', { name: 'Marcela Usa' }).click();
  await page.getByRole('textbox', { name: 'Ingrese una dirección' }).fill('cazadores 1987');
  await page.getByText('Cazadores 1987, Buenos Aires').click();
  await page.locator('.btn.btn-primary.rounded-btn.btn-freq-dest').click();
  await page.getByRole('cell', { name: 'Testing 2' }).click();
  await page.getByRole('cell', { name: 'Testing 2' }).click();
  await page.getByRole('button', { name: 'Seleccionar', exact: true }).click();
  await page.locator('.btn.btn-primary.rounded-btn.btn-freq-dest').click();
  await page.locator('.table-responsive').click();
  await page.locator('.table-responsive').dblclick();
  await page.getByRole('cell', { name: 'prueba' }).dblclick();
  await page.getByRole('cell', { name: 'Testing2' }).click();
  await page.getByRole('button', { name: 'Seleccionar', exact: true }).click();
  await page.locator('.data-with-icon-col.option-content-container.ng-tns-c27-9').click();
  await page.locator('.data-with-icon-col.option-content-container.ng-tns-c27-9').click();
  await page.locator('.highlighted > .data-with-icon-col').click();
  await page.getByRole('button', { name: 'Configurar', exact: true }).click();
  await page.getByRole('textbox', { name: 'General' }).click();
  await page.getByRole('textbox', { name: 'General' }).fill('viaje con destino frecuente');
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await page.getByRole('button', { name: 'Seleccionar Vehículo' }).click();
  await page.getByText('Ahora').first().click();
  await page.locator('#id_tab_add_travel').getByText('06:35 PM').click();
  await page.locator('.form-group > .form-group > .switch > .switch-label').first().click();
  await page.locator('.form-group > .form-group > .switch > .switch-label').first().click();
  await page.getByRole('spinbutton').fill('100');
  await page.locator('div:nth-child(3) > .row-main-container > .column-container > .padding-switch > div > .form-group > .switch > .switch-label').click();
  await page.getByRole('spinbutton').fill('100.02');
  await page.locator('.round-inline > div > .round > label').first().click();
  await page.locator('div:nth-child(2) > .round > label').first().click();
  await page.locator('.switch-handle').first().click();
  await page.locator('.switch-label').first().click();
  await page.getByRole('button', { name: 'Seleccionar Vehículo' }).click();
  await page.getByText('Premium $ 18,664.48 (0)').click();
  await page.getByRole('listitem').filter({ hasText: 'Standard $ 100.00 (3)' }).getByRole('img').click();
  await page.locator('.form-group > .form-group > .switch > .switch-label').first().click();
  await page.getByRole('spinbutton').fill('100');
  await page.getByRole('button', { name: 'Enviar Servicio' }).click();
  await page.getByText('Viaje Creado Exitosamente').click();
});